// <auto-generated />
using System;
using Autoveod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autoveod.Migrations
{
    [DbContext(typeof(AutoveodContext))]
    [Migration("20220127071720_Sisesaine")]
    partial class Sisesaine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Autoveod.Models.Veod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Aeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Algus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autonr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuhtEesnimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JuhtPerenimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valmis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Veod");
                });
#pragma warning restore 612, 618
        }
    }
}
